### ISSUE TITLE
error pulling image configuration: denied: unauthenticated: User cannot be authenticated with the token provided.

### ISSUE THREAD

**Issue by puggan** [php-actions/php-build#2]
My github-action for the step:
```
      - name: Composer install
        uses: php-actions/composer@v4
        with:
          args: --ignore-platform-reqs
```
failes with the error:
> error pulling image configuration: denied: unauthenticated: User cannot be authenticated with the token provided.

I get the same error if I localy run:
`docker pull ghcr.io/php-actions/php-build:v1`

![Screenshot from 2020-11-30 20-10-26](https://user-images.githubusercontent.com/866668/100653191-531cf280-3348-11eb-9949-5600e97e1b10.png)

![Screenshot from 2020-11-30 20-10-45](https://user-images.githubusercontent.com/866668/100653197-56b07980-3348-11eb-9dfc-36b62e7620d5.png)

![Screenshot from 2020-11-30 20-11-49](https://user-images.githubusercontent.com/866668/100653204-5912d380-3348-11eb-8a29-941877c099d6.png)
